server:
  port: 8888
  servlet:
    context-path: "/sell"
spring:
  freemarker:
    suffix: .ftl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  redis:
    host: 192.168.1.9
    port: 6379


project:
  wechatMpAuthorize: http://127.0.0.1:8888
  wechatOpenAuthorize: http://127.0.0.1:8888
  sell: http://127.0.0.1:8888

vchat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ


#use logback-spring.xml
#logging:
#  pattern:
#    console: "%d - %msg%n"
#    file: "test.log"
#    level: debug